--ZADANIE 1

--A

INSERT INTO USER_SDO_GEOM_METADATA VALUES (
    'FIGURY',
    'KSZTALT',
    MDSYS.SDO_DIM_ARRAY(
        MDSYS.SDO_DIM_ELEMENT('X', 0, 9, 0.01),
        MDSYS.SDO_DIM_ELEMENT('Y', 0, 8, 0.01)
    ),
    NULL
);

--B

SELECT SDO_TUNE.ESTIMATE_RTREE_INDEX_SIZE(3000000, 8192, 10, 2, 0) FROM DUAL;

--C

CREATE INDEX figury_idx ON figury(ksztalt) INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2;

--D

SELECT id FROM figury WHERE SDO_FILTER(ksztalt, SDO_GEOMETRY(2001, NULL, SDO_POINT_TYPE(3, 3, NULL), NULL, NULL)) = 'TRUE';
--Uzyskany wynik nie odpowiada rzeczywistości, gdyż ten punkt zawiera się tylko w jednej figurze.

--E

SELECT id FROM figury WHERE SDO_RELATE(ksztalt, SDO_GEOMETRY(2001, NULL, SDO_POINT_TYPE(3,3, NULL), NULL, NULL), 'mask=ANYINTERACT') = 'TRUE';
--Teraz wynik odpowiada rzeczywistości

--ZADANIE 2

--A

SELECT A.CITY_NAME AS MIASTO, SDO_NN_DISTANCE(1) AS ODL FROM MAJOR_CITIES A, MAJOR_CITIES B
WHERE SDO_NN(A.GEOM, B.GEOM, 'sdo_num_res=10 unit=km', 1) = 'TRUE'
    AND A.CITY_NAME <> 'Warsaw'
    AND B.CITY_NAME = 'Warsaw';

--B

SELECT A.CITY_NAME AS MIASTO FROM MAJOR_CITIES A, MAJOR_CITIES B
WHERE SDO_WITHIN_DISTANCE(A.GEOM, B.GEOM, 'distance=100 unit=km') = 'TRUE'
    AND A.CITY_NAME <> 'Warsaw'
    AND B.CITY_NAME = 'Warsaw';

--C

SELECT C.CNTRY_NAME AS KRAJ, M.CITY_NAME AS MIASTO
FROM COUNTRY_BOUNDARIES C, MAJOR_CITIES M
WHERE SDO_RELATE(M.GEOM, C.GEOM, 'mask=INSIDE') = 'TRUE'
    AND C.CNTRY_NAME = 'Slovakia';

--D

SELECT A.CNTRY_NAME AS PANSTWO, SDO_GEOM.SDO_DISTANCE(A.GEOM, B.GEOM, 1, 'unit=km') AS ODL
FROM COUNTRY_BOUNDARIES A, COUNTRY_BOUNDARIES B
WHERE SDO_RELATE(A.GEOM, B.GEOM, 'mask=ANYINTERACT') != 'TRUE'
    AND B.CNTRY_NAME = 'Poland';

--ZADANIE 3

--A

SELECT A.CNTRY_NAME, SDO_GEOM.SDO_LENGTH(SDO_GEOM.SDO_INTERSECTION(A.GEOM, B.GEOM, 1), 1, 'unit=km') AS ODLEGLOSC 
FROM COUNTRY_BOUNDARIES A, COUNTRY_BOUNDARIES B
WHERE SDO_FILTER(A.GEOM, B.GEOM) = 'TRUE'
    AND A.CNTRY_NAME <> 'Poland'
    AND B.CNTRY_NAME = 'Poland';

--B

SELECT CNTRY_NAME FROM COUNTRY_BOUNDARIES
WHERE SDO_GEOM.SDO_AREA(GEOM) = (
    SELECT MAX(SDO_GEOM.SDO_AREA(GEOM))
    FROM COUNTRY_BOUNDARIES);

--C

SELECT SDO_GEOM.SDO_AREA(SDO_AGGR_MBR(GEOM), 1, 'unit=SQ_KM') AS SQ_KM 
FROM MAJOR_CITIES WHERE CITY_NAME IN ('Lodz', 'Warsaw');

--D

SELECT SDO_GEOM.SDO_UNION(A.GEOM, B.GEOM, 1).SDO_GTYPE AS GTYPE
FROM COUNTRY_BOUNDARIES A, MAJOR_CITIES B
WHERE A.CNTRY_NAME = 'Poland'
    AND B.CITY_NAME = 'Prague';

--E

SELECT B.CITY_NAME, A.CNTRY_NAME
FROM COUNTRY_BOUNDARIES A, MAJOR_CITIES B
WHERE A.CNTRY_NAME = B.CNTRY_NAME
    AND SDO_GEOM.SDO_DISTANCE(
        SDO_GEOM.SDO_CENTROID(A.GEOM, 1), B.GEOM, 1) = (SELECT MIN(SDO_GEOM.SDO_DISTANCE(SDO_GEOM.SDO_CENTROID(A.GEOM, 1), B.GEOM, 1))
                                                          FROM COUNTRY_BOUNDARIES A, MAJOR_CITIES B
                                                          WHERE A.CNTRY_NAME = B.CNTRY_NAME
                                                      );

--F

SELECT NAME, SUM(DLUGOSC) AS DLUGOSC
FROM (SELECT B.NAME, SDO_GEOM.SDO_LENGTH(SDO_GEOM.SDO_INTERSECTION(A.GEOM, B.GEOM, 1), 1, 'unit=KM') AS DLUGOSC 
        FROM COUNTRY_BOUNDARIES A, RIVERS B
        WHERE SDO_RELATE(A.GEOM, B.GEOM, 'mask=ANYINTERACT') = 'TRUE'
        AND A.CNTRY_NAME = 'Poland')
GROUP BY NAME;
